// GENERATED FILE - DO NOT EDIT MANUALLY
// This file should be generated by running:
//   flutterfire configure
//
// To generate this file, install the FlutterFire CLI:
//   dart pub global activate flutterfire_cli
//
// Then run:
//   flutterfire configure
//
// This will create the proper Firebase configuration for your project.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// IMPORTANT: Replace this placeholder with the actual generated file
/// by running `flutterfire configure` in your project root.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAeNvoVKLL4Mfx1vhfswoDkS1CpUXUMvAU',
    appId: '1:784857267556:web:0998b5a7447df5301dce71',
    messagingSenderId: '784857267556',
    projectId: 'invtracker-b19d1',
    authDomain: 'invtracker-b19d1.firebaseapp.com',
    storageBucket: 'invtracker-b19d1.firebasestorage.app',
    measurementId: 'G-2ZXQ61VKKT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVyICKv0sQlJUAjxj1gYwGlekC_7hLPz4',
    appId: '1:784857267556:android:5ba7e064263d78f61dce71',
    messagingSenderId: '784857267556',
    projectId: 'invtracker-b19d1',
    storageBucket: 'invtracker-b19d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3axXv_AOdnHjP5AGSBErOHpGNlifsMvM',
    appId: '1:784857267556:ios:c81b06c6f4a60a001dce71',
    messagingSenderId: '784857267556',
    projectId: 'invtracker-b19d1',
    storageBucket: 'invtracker-b19d1.firebasestorage.app',
    androidClientId:
        '784857267556-11hac9h5j7bidre8g6imhu3442gurc6j.apps.googleusercontent.com',
    iosClientId:
        '784857267556-vjm61b2vf231rq5itm1ire0767oc0frn.apps.googleusercontent.com',
    iosBundleId: 'com.invtracker.invTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3axXv_AOdnHjP5AGSBErOHpGNlifsMvM',
    appId: '1:784857267556:ios:c81b06c6f4a60a001dce71',
    messagingSenderId: '784857267556',
    projectId: 'invtracker-b19d1',
    storageBucket: 'invtracker-b19d1.firebasestorage.app',
    androidClientId:
        '784857267556-11hac9h5j7bidre8g6imhu3442gurc6j.apps.googleusercontent.com',
    iosClientId:
        '784857267556-vjm61b2vf231rq5itm1ire0767oc0frn.apps.googleusercontent.com',
    iosBundleId: 'com.invtracker.invTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAeNvoVKLL4Mfx1vhfswoDkS1CpUXUMvAU',
    appId: '1:784857267556:web:537476d9eb80e5491dce71',
    messagingSenderId: '784857267556',
    projectId: 'invtracker-b19d1',
    authDomain: 'invtracker-b19d1.firebaseapp.com',
    storageBucket: 'invtracker-b19d1.firebasestorage.app',
    measurementId: 'G-K2VF1ERRED',
  );

  /// OAuth Client IDs for Google Sign-In
  /// These are PUBLIC identifiers from Firebase project configuration.
  /// NOT secrets - safe to include in source control.

  /// Web OAuth Client ID for web platform
  /// Used in: google_sign_in initialization on web (clientId parameter)
  /// Source: Firebase Console > Authentication > Sign-in method > Google > Web SDK configuration
  static const String webOAuthClientId =
      '20057918856-r6qh2gt5eqk2o3oiq8fkt8pgfhquja6a.apps.googleusercontent.com';

  /// Android/iOS Server Client ID (Web OAuth Client ID)
  /// Used in: google_sign_in initialization on mobile (serverClientId parameter)
  ///
  /// IMPORTANT: This is the Web Client ID (client_type: 3 in google-services.json)
  /// Google Sign-In v7+ REQUIRES this on Android to prevent:
  /// GoogleSignInException: "serverClientId must be provided on Android"
  ///
  /// Source: google-services.json (client_type: 3) / Firebase Console
  /// See: https://github.com/flutter/flutter/issues/172073
  static const String mobileServerClientId =
      '784857267556-dkge5l37c12n1ohrljle8s6nim0cgq84.apps.googleusercontent.com';
}
